#!/usr/bin/env python3
from typing import List

class Router:
    def __init__(self, name:str):
        self.name:str = name
        self.DV = {}
        return
    
class Edge:
    def __init__(self, router1:'Router', router2:'Router', cost:int):
        self.router1:Router = router1
        self.router2:Router = router2
        
        # Set in alphabetical order
        if self.router1.name > self.router2.name:
            self.router1, self.router2 = self.router2, self.router1
        self.cost:int = cost
    
    def __repr__(self) -> str:
        return str((self.router1.name, self.router2.name))


def read_until_(stop_line:str):
    # Read data from standard input
    data = []
    while True:
        line = input().strip()
        if line == stop_line:
            return data
        data.append(line)
    return data

if __name__ == '__main__':
    init_section = read_until_(stop_line='START')
    start_section = read_until_(stop_line='UPDATE')
    end_section = read_until_(stop_line='END')